<!doctype html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Codea Technologies</title>
        <link rel="shortcut icon" href="assets/images/codea-icon.png" type="image/x-icon">
        
        <!-- CSS -->
        <link rel="stylesheet" href="assets/css/bootstrap.css">
        <link rel="stylesheet" href="assets/css/style.css">
        
        <script src="https://kit.fontawesome.com/085049fa59.js"></script>
    
    </head>
    
    <body>
    	
        <?php include('header.php'); ?>
        
        <section class="casestudy-banner4">
        <div class="container">
        	
            <div class="cloud-head">
            	
                <h1 style="width:75%;">The mobile operation, control and maintenance of automated systems</h1>
                
            </div>
            
        </div>
        </section>
        
        <section class="mt-5 mb-5">
        <div class="container">
        	
            <div class="row mb-5">
            	
                <div class="col-md-9">
                
                	<h1 class="mb-3 mt-3">About The Company</h1>
                    <p>
                    	Our Client located in NY, USA has been developing a global standard for the mobile operation, control and maintenance of automated systems with the help of an ordinary mobile device. The company offered solutions to airports, warehouses, distribution centres, manufacturing operations and power stations, water treatment facilities or renewable energy farms. The environments in which the system operates are places where downtime is a critical issue.
                    </p>
                    
                    <h4 class="mt-5 mb-2">PARTNERSHIP OVERVIEW</h4>
                    <p>
                    	The dedicated development team at Codea has been working on enhancing clients enterprise asset management solutions. In addition, the team created a brand new software product, including both server-side and a highly customizable and flexible mobile client. During the collaboration period, Codea:
                    </p>
                    
                    <p>
                    	<b>Developed</b> full life cycle of the approved solution including design, development, testing and deployment both server-side and client.
                    </p>
                    
                    <p>
                    	<b>The designed</b> architecture of ESB-like integration platform using well-known industry standards and patterns to match integration challenges with various CMMS systems.
                    </p>
                    
                    <p>
                    	<b>Performed</b> R&amp;D of various technologies and solutions to match business needs.
                    </p>
                    
                    <p>
                    	<b>Elaborated</b> test cases design of the existing system along with the brand new.
                    </p>
                    
                    <p>
                    	<b>Worked</b> on the Asset Health Dashboard.
                    </p>
                    
                    <p>
                    	<b>Developed different plugins and provided</b> new highly-customizable mobile user interface.
                    </p>
                    
                    <h4 class="mt-5 mb-2">PRODUCT OVERVIEW</h4>
                    
                    <p>
                    	LOGOS is a smart enterprise solution that enables maintenance teams to incorporate real-time data into their workflows. The product has two modules which are LOGOS Map2Assets and  Map2Mobile. 
                    </p>
                    
                    <p>
                    	Map2Assets allows maintenance teams to leverage the data generated by the PLC/SCADA sensors. This enables them to monitor the health of assets by analysing a number of indicators such as cycle counts, runtime hours, fuel consumption, temperature, and pressure readings.
                    </p>
                    
                    <p>
                    	Condition data generated by Map2Assets can also be sent directly to the technicians with Map2Mobile. This solution combines alarms from SCADA systems with EAM/CMMS data, including work orders, asset history and spare parts and sends it to technicians’ smart devices, reducing unplanned downtime by as much as 65 Percent.
                    </p>
                    
                    <p>
                    	Using LOGOS Map2, maintenance teams have mobile access to the CMMS or EAM system. The solution enables seamless workflows to be completed on mobile devices, giving maintenance teams the time needed to respond to fault notifications while on the go. The module allows enterprises to plan and coordinate asset maintenance more effectively, reduce unscheduled downtime, and improve response times to problems or system failures. 
                    </p>
                    
                </div>
                
                <div class="col-md-3">
                	
                    <div>
                    <h4 class="codea-color1">Key features</h4>
                    <hr>
                    <div class="row mt-3">
                        
                        <div class="col-md-3 mb-3"><img src="assets/images/case-study-icon-08.png" alt="" class="img-fluid" /></div>
                        <div class="col-md-9 mb-3"><h2 style="line-height:35px;">Asset Management</h2></div>
                        
                        <div class="col-md-3 mb-3"><img src="assets/images/case-study-icon-09.png" alt="" class="img-fluid" /></div>
                        <div class="col-md-9 mb-3"><h2 style="line-height:35px;">Asset Health Dashboard</h2></div>
                        
                        <div class="col-md-3 mb-3"><img src="assets/images/case-study-icon-10.png" alt="" class="img-fluid" /></div>
                        <div class="col-md-9 mb-3"><h2 style="line-height:35px;">IoT Interaction</h2></div>
                        
                        <div class="col-md-3 mb-3"><img src="assets/images/case-study-icon-11.png" alt="" class="img-fluid" /></div>
                        <div class="col-md-9 mb-3"><h2 style="line-height:35px;">Preventive Maintenance</h2></div>
                        
                        <div class="col-md-3 mb-3"><img src="assets/images/case-study-icon-04.png" alt="" class="img-fluid" /></div>
                        <div class="col-md-9 mb-3"><h2 style="line-height:35px;">Planning</h2></div>
                        
                        <div class="col-md-3 mb-3"><img src="assets/images/case-study-icon-05.png" alt="" class="img-fluid" /></div>
                        <div class="col-md-9 mb-3"><h2 style="line-height:35px;">MIS</h2></div>
                        
                    </div>
                    </div>
                    
                    <div class="mt-4">
                    	<b>Industry:</b> Industrial Automation, Asset Management<br style="margin-bottom:15px;">
                        <b>Headquarters:</b> New York City, USA<br style="margin-bottom:15px;">
                        <b>Market:</b> USA<br style="margin-bottom:15px;">
                    </div>
                    
                    <div class="mt-5">
                    	<h2>Technologies:</h2>
						KOTLIN / SWIFT / .NET / Apache Solr / ASP.NET Web API / DevExpress / JavaScript ES6 / MS SQL Server / WCF
                    </div>
                    
                </div>
            	
            </div>
            
        </div>
        </section>
        
        <?php include('footer.php'); ?>
        
        <!-- JAVASCRIPT -->
        <script src="assets/js/jquery-3.3.1.slim.min.js" type="text/javascript"></script>
        <script src="assets/js/bootstrap.js" type="text/javascript"></script>
        
        <script src="assets/js/menu.js" type="text/javascript"></script>
        
    </body>
  
</html>